name: KCM
channels:
  - huggingface
  - pytorch
  - https://conda.rosettacommons.org
  - bioconda
  - conda-forge
  - https://levinthal:paradox@conda.rosettacommons.org
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20211102.0
  - antlr-python-runtime=4.9.3
  - arrow-cpp=8.0.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - biotite=0.31.0
  - blas=1.0=mkl
  - blosc=1.21.3
  - boost-cpp=1.73.0
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - certifi=2020.6.20
  - chardet=4.0.0
  - colorama=0.4.6
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dataclasses=0.8
  - datasets=2.6.1
  - dbus=1.13.18
  - decorator=4.4.2
  - dill=0.3.6
  - einops=0.6.1
  - exceptiongroup=1.2.0
  - expat=2.5.0
  - fairscale=0.4.3
  - fftw=3.3.10
  - filelock=3.9.0
  - fontconfig=2.14.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - glog=0.5.0
  - grpc-cpp=1.46.3
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hhsuite=3.3.0
  - hmmer=3.3.2
  - huggingface_hub=0.16.4
  - hydra-core=1.3.2
  - icu=58.2
  - idna=3.6
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=6.0.0
  - iniconfig=2.0.0
  - joblib=1.1.0
  - jpeg=9e
  - kalign2=2.04
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=8.5.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libiconv=1.17
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libpng=1.6.42
  - libpq=12.17
  - libprotobuf=3.20.3
  - libsqlite=3.44.2
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.4
  - multiprocess=0.70.14
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - networkx=2.5.1
  - nspr=4.35
  - nss=3.97
  - numpy-base=1.21.5
  - ocl-icd=2.3.1
  - ocl-icd-system=1.0.0
  - omegaconf=2.3.0
  - openmm=7.5.1
  - openssl=3.0.15
  - orc=1.7.4
  - packaging=23.2
  - pandas=1.3.5
  - pcre2=10.42
  - pdbfixer=1.7
  - perl=5.32.1
  - pillow=9.4.0
  - pip=23.3.2
  - pluggy=1.0.0
  - ply=3.11
  - pthread-stubs=0.4
  - pyarrow=8.0.0
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrosetta=2020.10+release.46415fa
  - pysocks=1.7.1
  - pytest=7.4.3
  - python=3.7.13
  - python-blosc=1.8.3
  - python-dateutil=2.8.2
  - python-xxhash=2.0.2
  - python_abi=3.7
  - pytorch=1.12.1
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - responses=0.13.3
  - sacremoses=master
  - setuptools=59.5.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.44.2
  - tbb=2021.8.0
  - tk=8.6.13
  - tokenizers=0.13.1
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - transformers=4.28.1
  - typing_extensions=4.3.0
  - utf8proc=2.6.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.0
  - xz=5.4.5
  - yaml=0.2.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - about-time==4.2.1
      - absl-py==2.0.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - alive-progress==3.1.5
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==23.1.0
      - autograd==1.6.2
      - biopython==1.79
      - blosum==2.0.2
      - cachetools==5.3.2
      - charset-normalizer==2.0.12
      - click==8.1.7
      - cma==3.2.2
      - contextlib2==21.6.0
      - deepspeed==0.5.9
      - deprecated==1.2.14
      - dllogger==1.0.0
      - dm-tree==0.1.6
      - docker-pycreds==0.4.0
      - fair-esm==2.0.0
      - flask==2.2.5
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - future==0.18.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.25.2
      - google-auth-oauthlib==0.4.6
      - grapheme==0.6.0
      - grpcio==1.60.0
      - gunicorn==22.0.0
      - hjson==3.1.0
      - itsdangerous==2.1.2
      - jinja2==3.1.4
      - markdown==3.4.4
      - markupsafe==2.1.3
      - ml-collections==0.1.0
      - multidict==6.0.4
      - ninja==1.11.1.1
      - numpy==1.21.2
      - oauthlib==3.2.2
      - openfold==1.0.0
      - pathtools==0.1.2
      - promise==2.3
      - protobuf==3.20.3
      - psutil==5.9.7
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydeprecate==0.3.1
      - pymoo==0.6.1.2
      - pytorch-lightning==1.5.10
      - pyyaml==5.4.1
      - requests==2.26.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.7.1
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - shortuuid==1.0.11
      - smmap==5.0.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - torchmetrics==0.11.4
      - tqdm==4.62.2
      - triton==1.0.0
      - typing-extensions==3.10.0.2
      - urllib3==1.26.18
      - wandb==0.12.21
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - yarl==1.9.4
